--- 
engines: 
  brakeman: 
    enabled: true
  bundler-audit: 
    enabled: true
  duplication: 
    config: 
      languages: 
        - ruby
        - javascript
    enabled: true
  eslint: 
    enabled: true
  exclude_paths: 
    - config/
    - db/
    - features/
    - node_modules/
    - spec/
    - vendor/
    - tmp/
    - builds/
    - public/
    - log/
  ratings: 
    paths: 
      - "**.erb"
      - "**.rb"
      - "**.js"
  reek: 
    enabled: true
  rubocop: 
    enabled: true
