---
engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  reek:
    enabled: true   
ratings:
  paths:
  - "**.erb"
  - "**.rb"
  - "**.js"
exclude_paths:
- config/**/*
- db/**/*
- node_modules/**/*
- spec/**/*
- vendor/**/*
- .yarn-cache/
- tmp/**/*
- builds/**/*
- public/**/*
- shared/**/*
